### ISSUE TITLE
Components>Buttons> icon-only button with '.hidden' label

### ISSUE THREAD

**Issue by IngridJac** [yoshino-digital/yoi#17]
I wonder why do we need to add a hidden label in the icon-only button.  Wouldn't it be enough just to put the icon?

![screenshot-buttons](https://user-images.githubusercontent.com/17355181/38417056-2a49433e-3997-11e8-8e45-27a8124e7049.png)

Same question for **FlipBtns**.

![screenshot-flipbuttons](https://user-images.githubusercontent.com/17355181/38417158-888df3fe-3997-11e8-92c6-b93e18e15db7.png)

**Comment by reimar** [comment]
I chose to introduce this practice for two reasons:

* to still include meaningful label text in the document even if the label is visually hidden – it helps screen readers and produces a nice fallback if no CSS is available
* to be able to target a button that has only an icon but no visible label without using a modifier class like `button--onlyIcon` (see src/components/button/button.less/ line 128):

```css
    // only icons, hidden or no label

    .hidden + .icon,
    .icon:only-child {
        margin-left: -1rem;
        width: 2.3rem;
    }

    &.btn--small .hidden + .icon,
    &.btn--small .icon:only-child {
        margin-left: -.4rem;
        width: 1.6rem;
    }

    &.btn--medium .hidden + .icon,
    &.btn--medium .icon:only-child {
        margin-left: -1.2rem;
        width: 3rem;
    }

    &.btn--large .hidden + .icon,
    &.btn--large .icon:only-child {
        margin-right: -2rem;
        margin-left: -2rem;
        width: 4rem;
    }
```
